---
- name: Import GPG Key
  rpm_key:
    state: present
    key: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: "Install chrome repo(CentOS7)"
  template:
    src: "google-chrome.repo"
    dest: "/etc/yum.repos.d/google-chrome.repo"
    owner: root
    group: root
    mode: 0644

- name: Install yum chrome
  yum:
    name: google-chrome-stable
    state: present
